using System;
using UnityEngine;
using System.Collections;
using System.IO;
using System.Security.Cryptography;
using System.Text;

public enum FileType {
    Image, Video, Code, Document, Chompymon
}
[Serializable]
public class Demon {

    public string Name;
    public int Size;
    public int Multiplier;
    public FileType Craving;

    readonly string filePath;

    public Demon(string filePath) {
        this.filePath = filePath;
    }
    
    public static Demon CreateDemon() {
        var newFile = File.CreateText(Application.persistentDataPath + "/NEW.chompymon");
        newFile.Close();
        var info = new FileInfo(Application.persistentDataPath + "/NEW.chompymon");
        var creation = info.CreationTimeUtc.Ticks;
        var key = creation + SystemInfo.deviceUniqueIdentifier;
        using (var r = new WithRandomSeed(key.GetHashCode())) {
            var name = PREFIXES.Random() + SUFFIXES.Random();
            var path = Application.persistentDataPath + $"/{name}.chompymon";
            File.Move(Application.persistentDataPath + "/NEW.chompymon", path);
            var demon = new Demon(path) {
                Name = name,
            };
            Save(demon);
            return demon;
        }
    }

    public static void Save(Demon d) {
        var text = $"bunchoffillerstuffherethatdoesntreallymatterormaybeitdoesidunnojustdontchangeit-{d.Name}-{d.Size}-{d.Multiplier}-{(int)d.Craving}";
        var info = new FileInfo(Application.persistentDataPath + $"/{d.Name}.chompymon");
        var creation = info.CreationTimeUtc.Ticks;
        var key = creation + SystemInfo.deviceUniqueIdentifier;
        var encryptedText = Encrypt(text, key);
        File.WriteAllText(d.filePath, encryptedText);
    }

    public static Demon Load(FileInfo info) {
        try {
            var creation = info.CreationTimeUtc.Ticks;
            var key = creation + SystemInfo.deviceUniqueIdentifier;
            var decryptedText = Decrypt(File.ReadAllText(info.FullName), key);
            var split = decryptedText.Split('-');
            return new Demon(info.FullName) {
                Name = split[1],
                Size = int.Parse(split[2]),
                Multiplier = int.Parse(split[3]),
                Craving = (FileType)int.Parse(split[4]),
            };
        } catch (Exception e) {
            return null;
        }
    }

    public static string Encrypt(string decryptedText, string key) {
        var sb = new StringBuilder(100);
        var i = 0;
        foreach (var c in decryptedText) {
            sb.Append((char)(c + key[i]));
            i = (i + 1) % key.Length;
        }
        return sb.ToString();
    }

    public static string Decrypt(string encryptedText, string key) {
        var sb = new StringBuilder(100);
        var i = 0;
        foreach (var c in encryptedText) {
            sb.Append((char)(c - key[i]));
            i = (i + 1) % key.Length;
        }
        return sb.ToString();
    }

    public static readonly string[] PREFIXES = {
        "AA",
        "ABA",
        "ABEZE",
        "ABRA",
        "ABY",
        "AD",
        "ADRAM",
        "AES",
        "AGA",
        "AGAR",
        "AGI",
        "AG",
        "AH",
        "AI",
        "AKA",
        "AK",
        "AKO",
        "AL",
        "ALA",
        "ALL",
        "AMAY",
        "AMDU",
        "AMY",
        "ANAM",
        "AND",
        "ANDREA",
        "ANDRO",
        "AN",
        "ANTI",
        "AR",
        "ARM",
        "ARU",
        "AS",
        "ASA",
        "ASB",
        "ASMO",
        "ASTA",
        "ASU",
        "AZ",
        "AZA",
        "AZI",
        "BAAL",
        "BA",
        "BAL",
        "BAN",
        "BAP",
        "BAR",
        "BAT",
        "BEEL",
        "BE",
        "BEHE",
        "BEL",
        "BH",
        "BI",
        "BO",
        "BU",
        "BUSH",
        "CAAC",
        "CAASSI",
        "CA",
        "CHA",
        "CHE",
        "CHORO",
        "CIME",
        "CLASS",
        "COR",
        "CRO",
        "CUL",
        "DAE",
        "DA",
        "DAJ",
        "DAN",
        "DECA",
        "DEM",
        "DEMO",
        "DE",
        "DI",
        "DRE",
        "DZOA",
        "EIS",
        "EL",
        "ELI",
        "FLAU",
        "FOCA",
        "FOR",
        "FO",
        "FUR",
        "GA",
        "GAD",
        "GAM",
        "GH",
        "GLA",
        "GOR",
        "GRE",
        "GRI",
        "GUA",
        "GUS",
        "HAA",
        "HAL",
        "HI",
        "IB",
        "IF",
        "INCU",
        "IP",
        "JIKI",
        "JI",
        "KAB",
        "KA",
        "KAS",
        "KI",
        "KO",
        "KRA",
        "KRO",
        "KUK",
        "KUM",
        "LEC",
        "LEG",
        "LEM",
        "LEO",
        "LER",
        "LEV",
        "LEY",
        "LIL",
        "LJU",
        "LOU",
        "LUC",
        "MAL",
        "MAM",
        "MAR",
        "MAS",
        "MAT",
        "MEP",
        "MER",
        "MOL",
        "MON",
        "MO",
        "MU",
        "NA",
        "NI",
        "ON",
        "OR",
        "OS",
        "PAI",
        "PAZ",
        "PEL",
        "PEN",
        "PHE",
        "PIT",
        "POC",
        "PON",
        "PRE",
        "PRU",
        "PUL",
        "RAH",
        "RAK",
        "RAN",
        "RA",
        "RO",
        "RU",
        "SA",
        "SE",
        "SH",
        "SHE",
        "SIL",
        "SIT",
        "STH",
        "STI",
        "STO",
        "SUA",
        "SUC",
        "SUR",
        "TAN",
        "TIT",
        "TOY",
        "TUC",
        "UKO",
        "VAL",
        "VAN",
        "VAP",
        "VAS",
        "VEP",
        "VIN",
        "WEN",
        "YEQ",
        "ZAG",
        "ZAH",
        "ZEP",
        "ZIM",
        "ZU",
    };
    public static readonly string[] SUFFIXES = {
        "MON",
        "DDON",
        "THIBOU",
        "XAS",
        "ZOU",
        "MELECH",
        "HMA",
        "LIAREPT",
        "ES",
        "EL",
        "RAT",
        "RIMAN",
        "M",
        "EM",
        "MAN",
        "VAN",
        "A",
        "AL",
        "STOR",
        "OCER",
        "MON",
        "SIAS",
        "MELECH",
        "HAKA",
        "RAS",
        "LPHUS",
        "MALIUS",
        "GRA",
        "CHRIST",
        "CHON",
        "AROS",
        "NASURA",
        "AG",
        "KKU",
        "MODAI",
        "DEUS",
        "ROTH",
        "RA",
        "AZ",
        "ZEL",
        "BI",
        "KASURA",
        "KU",
        "LAM",
        "BERITH",
        "LI",
        "SHEE",
        "HOMET",
        "BAS",
        "BATOS",
        "RONG",
        "THIN",
        "HYM",
        "ZEBUB",
        "HEMOTH",
        "RIT",
        "LETH",
        "LIAL",
        "PHEGOR",
        "RITH",
        "OOT",
        "FRONS",
        "RUTA",
        "TIS",
        "ER",
        "KAVAC",
        "NE",
        "YASTA",
        "RINOLAAS",
        "MOLAR",
        "IM",
        "MIO",
        "RUN",
        "MOSH",
        "NZON",
        "IES",
        "JES",
        "YALABOLAS",
        "SON",
        "CELL",
        "SU",
        "VA",
        "GON",
        "JAL",
        "JAL",
        "TALION",
        "RABIA",
        "IURGE",
        "GORGON",
        "VIL",
        "V",
        "KAVAC",
        "VITS",
        "HETH",
        "GOS",
        "ROS",
        "LOR",
        "AII",
        "RAS",
        "CAS",
        "NEUS",
        "RAS",
        "CAS",
        "FUR",
        "AP",
        "REEL",
        "IGIN",
        "OUL",
        "SSIA",
        "GON",
        "MORY",
        "GORI",
        "LICHU",
        "YOTA",
        "ION",
        "OYN",
        "GENTI",
        "PHAS",
        "NN",
        "LIS",
        "RIT",
        "BUS",
        "OS",
        "NINKI",
        "NN",
        "ANDHA",
        "HANDA",
        "LI",
        "ADYA",
        "MARIS",
        "KABIEL",
        "MPUS",
        "NI",
        "UDH",
        "BHAKARNA",
        "HIES",
        "ION",
        "PO",
        "NARD",
        "AIE",
        "AJE",
        "IATHAN",
        "AK",
        "IM",
        "IN",
        "ITH",
        "BI",
        "VIERS",
        "IFER",
        "IFUGE",
        "APHAR",
        "EPHAR",
        "PHAS",
        "THUS",
        "MON",
        "A",
        "CHOSIAS",
        "ICHA",
        "THIM",
        "IH",
        "TEMA",
        "HIM",
        "HISTOPHELES",
        "IHEM",
        "OCH",
        "TPELIER",
        "RAX",
        "RMUR",
        "AMAH",
        "BERIUS",
        "MTAR",
        "NURTA",
        "I",
        "OSKELIS",
        "CUS",
        "IAS",
        "OBAS",
        "E",
        "MON",
        "UZU",
        "ESIT",
        "EMUE",
        "NEX",
        "HIUS",
        "ONG",
        "TIANAK",
        "TA",
        "FLAS",
        "OMAN",
        "AB",
        "SHASA",
        "GDA",
        "UM",
        "NOVE",
        "SALKA",
        "BNOCK",
        "LEMENCE",
        "LEOS",
        "MAEL",
        "TAN",
        "IR",
        "MYAZA",
        "AITAN",
        "AX",
        "DIM",
        "VER",
        "RI",
        "ENNO",
        "HI",
        "LAS",
        "NGGI",
        "CUBUS",
        "GAT",
        "NIN",
        "IVILLUS",
        "OL",
        "HULCHA",
        "BACH",
        "AC",
        "EFAR",
        "TH",
        "ULA",
        "SAGO",
        "AR",
        "E",
        "DIGO",
        "ON",
        "AN",
        "HAK",
        "AR",
        "INIAR",
    };
}